### ISSUE TITLE
Project name confusing with the Redox OS project

### ISSUE THREAD

**Issue by UtherII** [LucasBullen/corrosion#24]
While the Redox name is nice for a project in Rust, it is already used by another great project in Rust : the [Redox OS](https://www.redox-os.org/) project. Since the Redox project is currently pretty active, another unrelated project with a really similar name is really confusing.

The project is still young, having a name change now would not be too harmful.

**Comment by LucasBullen** [comment]
Completely correct. We are changing the project name now and is being addressed here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=529674

**Comment by LucasBullen** [comment]
Project has been renamed to Corrosion as of f06a65b
